-- ==========================================
-- ATUALIZAÇÕES PARA SISTEMA DE CLIENTE
-- ==========================================
--
-- NOTA: Este arquivo continha migrações que foram incorporadas ao schema.sql
-- As alterações abaixo já estão incluídas no schema.sql atualizado:
--
-- ✅ ALTER TABLE clientes ADD COLUMN senha VARCHAR(255) DEFAULT NULL AFTER telefone;
-- ✅ ALTER TABLE clientes ADD COLUMN ativo BOOLEAN DEFAULT TRUE AFTER senha;
-- ✅ CREATE TABLE IF NOT EXISTS carrinho (...);
-- ✅ CREATE INDEX idx_carrinho_cliente ON carrinho(cliente_id);
--
-- Este arquivo pode ser removido ou mantido apenas para referência histórica.
-- Para novas instalações, use apenas schema.sql + seed.sql
--
-- ==========================================
